"use client";
import React, { useState } from "react";
import SelectOption from "./_components/SelectOption";
import { Button } from "@/components/ui/button";
import TopicInput from "./_components/TopicInput";
import { v4 as uuidv4 } from "uuid";
import { useUser } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

function CreateCourse() {
  const [step, setStep] = useState(0);
  const [formData, setFormData] = useState({});
  const { user } = useUser();
  const [loading, setLoading] = useState(false);

  const router = useRouter();
  const [generatedTopics, setGeneratedTopics] = useState([]);
  const [genLoading, setGenLoading] = useState(false);
  const handleUserInput = (fieldName, fieldValue) => {
    setFormData((prev) => ({
      ...prev,
      [fieldName]: fieldValue,
    }));
    console.log(formData);
  };

  const GenerateCourseOutline = async () => {
    // Call server AI endpoint to generate course layout, then save locally so Dashboard shows it.
    const courseId = uuidv4();
    setLoading(true);
    const topic = formData.topic || "Untitled";
    const difficulty = formData.difficultyLevel || "Moderate";
    const courseType = formData.courseType || "Other";

    try {
      const createdBy = user?.primaryEmailAddress?.emailAddress || user?.id || "local";
      const resp = await fetch("/api/generate-course-ai", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic, difficultyLevel: difficulty, courseType, createdBy }),
      });

      if (!resp.ok) {
        const errBody = await resp.json().catch(() => ({}));
        console.error("AI route returned error:", errBody);
        toast.error("Failed to generate course via AI. Falling back to local generator.");
        // fallback to previous simple client generator
        const fallbackLayout = {
          courseTitle: topic,
          courseSummary: `Auto-generated study material for '${topic}' (Difficulty: ${difficulty}).`,
          topics: [topic, `${topic} - Basics`, `${topic} - Advanced`],
          chapters: [],
        };
        const newCourse = { id: Date.now(), courseId, status: "Completed", courseLayout: fallbackLayout };
        const saved = localStorage.getItem("prepgen_local_courses");
        const arr = saved ? JSON.parse(saved) : [];
        arr.unshift(newCourse);
        localStorage.setItem("prepgen_local_courses", JSON.stringify(arr));
        router.replace("/dashboard");
        return;
      }

      const json = await resp.json().catch(() => ({}));
      const courseLayout = json.courseLayout;
        // If topics were generated by user, prefer those
        if (generatedTopics && generatedTopics.length > 0) {
          courseLayout.topics = generatedTopics;
        }
      const newCourse = { id: Date.now(), courseId, status: "Completed", courseLayout };
      const saved = localStorage.getItem("prepgen_local_courses");
      const arr = saved ? JSON.parse(saved) : [];
      arr.unshift(newCourse);
      localStorage.setItem("prepgen_local_courses", JSON.stringify(arr));
      toast.success("Course generated and saved — visible in Dashboard.");
      router.replace("/dashboard");
    } catch (e) {
      console.error("GenerateCourseOutline error", e);
      toast.error("Failed to generate course. Try again later.");
    } finally {
      setLoading(false);
    }
  };

  const generateTopics = async () => {
    const subject = formData.topic || "General Topics";
    setGenLoading(true);
    try {
      const resp = await fetch("/api/openai/generate-topics", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ subject, count: 8 }),
      });

      if (!resp.ok) {
        const errBody = await resp.json().catch(() => ({}));
        throw { response: { data: errBody } };
      }

      const data = await resp.json();
      const topics = data?.topics || [];
      setGeneratedTopics(topics.map((t) => String(t).trim()));
      toast.success(`Generated ${topics.length} topics`);
    } catch (e) {
      // Show server-provided details when available, otherwise a generic message
      const respErr = e?.response?.data || null;
      const details = respErr?.details || respErr?.error || e?.message;

      // If we specifically hit OpenAI quota, fallback to local topic generator
      const code = respErr?.code || respErr?.error?.code || respErr?.error?.type || null;
      if (code === "insufficient_quota" || code === "insufficient_quota") {
        // build a small local fallback set
        const fallback = [
          subject,
          `${subject} - Basics`,
          `${subject} - Advanced`,
          `Key Concepts of ${subject}`,
          `${subject} - Practice Questions`,
        ].map((t) => String(t).trim());
        setGeneratedTopics(fallback);
        toast.error("AI quota exhausted — using local fallback topics.");
      } else {
        toast.error(details || "Failed to generate topics");
        // ensure we clear any partial results
        setGeneratedTopics([]);
      }
    } finally {
      setGenLoading(false);
    }
  };

  const removeGeneratedTopic = (index) => {
    setGeneratedTopics((prev) => prev.filter((_, i) => i !== index));
  };

  return (
    <div className="flex flex-col items-center p-5 md:px-24 lg:px-36 mt-20">
      <h2 className="font-bold text-4xl text-primary ">
        Start Building your Personal Study Material
      </h2>
      <p className="text-gray-500 text-lg">
        Fill all details in order to generate study material for your next
        project
      </p>
      <div className="mt-10">
        {step == 0 ? (
          <SelectOption
            selectedStudyType={(value) => handleUserInput("courseType", value)}
          />
        ) : (
          <div>
            <TopicInput
              setDifficultyLevel={(value) =>
                handleUserInput("difficultyLevel", value)
              }
              setTopic={(value) => handleUserInput("topic", value)}
            />

            <div className="mt-4 flex items-center gap-3">
              <Button onClick={generateTopics} disabled={genLoading}>
                {genLoading ? "Generating…" : "Generate topics (OpenAI)"}
              </Button>
              <p className="text-sm text-gray-500">Use AI to suggest topic titles.</p>
            </div>

            {generatedTopics && generatedTopics.length > 0 && (
              <div className="mt-4 w-full">
                <h3 className="font-semibold">Generated topics</h3>
                <div className="flex flex-wrap gap-2 mt-2">
                  {generatedTopics.map((t, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-2 rounded-full bg-sky-100 text-sky-800 px-3 py-1"
                    >
                      <span className="text-sm">{t}</span>
                      <button
                        onClick={() => removeGeneratedTopic(i)}
                        className="ml-2 text-red-600 font-bold"
                        aria-label={`Remove topic ${t}`}
                      >
                        ×
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <div className="flex justify-between w-[60%] mt-32">
        {step != 0 ? (
          <Button variant="outline" onClick={() => setStep(0)}>
            Previous
          </Button>
        ) : (
          "-"
        )}
        {step == 0 ? (
          <Button onClick={() => setStep(1)}>Next</Button>
        ) : (
          <Button onClick={GenerateCourseOutline}>Generate</Button>
        )}
      </div>
    </div>
  );
}

export default CreateCourse;
